---
# 18_endpoint_pam_exec - Service Handlers

- name: restart sshd
  ansible.builtin.service:
    name: "{{ 'ssh' if ansible_facts['os_family'] == 'Debian' else 'sshd' }}"
    state: restarted
  listen: restart sshd
