---
# Ansible Galaxy requirements for zti-config
# Install: ansible-galaxy install -r requirements.yml

collections:
  # Community general collection (essential modules)
  - name: community.general
    version: ">=8.0.0"

  # Docker management
  - name: community.docker
    version: ">=3.0.0"

  # PostgreSQL management (for Authentik)
  - name: community.postgresql
    version: ">=3.0.0"

  # System administration
  - name: ansible.posix
    version: ">=1.5.0"
